version: "3"

services:
  react-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: capstone--app-image
    container_name: my-react-app-container
    ports:
      - "80:3000"
    volumes:
      - ./src:/app/src

