version: "3"

services:
  react-container:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: capstone-app-image
    container_name: my-react-app-container
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src

